domain/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('domain.views',
    url(r'^$', 'home', name='home'),

    url(r'^people/create/$', 'people_create', name='people_create'),
    url(r'^people/(?P<people_id>\d+)/edit/$', 'people_edit', name='people_edit'),
    url(r'^people/(?P<people_permalink>[A-Za-z0-9-_.]+)/$', 'people_detail', name='people_detail'),
    url(r'^people/$', 'people_list', name='people_list'),
    url(r'^people/(?P<people_permalink>[A-Za-z0-9-_.]+)/meter/(?P<meter_permalink>[A-Za-z0-9-_.]+)/$', 'people_detail', name='people_meter'),

    url(r'^topic/create/$', 'topic_create', name='topic_create'),
    url(r'^topic/(?P<topic_id>\d+)/edit/$', 'topic_edit', name='topic_edit'),
    url(r'^topic/(?P<topic_id>\d+)/edit/from/(?P<statement_id>\d+)/$', 'topic_edit_from_statement', name='topic_edit_from_statement'),
    url(r'^topic/(?P<topic_id>\d+)/$', 'topic_detail', name='topic_detail'),
    url(r'^topic/(?P<topic_id>\d+)/revision/(?P<topicrevision_id>\d+)/$', 'topicrevision_detail', name='topicrevision_detail'),
    url(r'^topic/(?P<topic_id>\d+)/revision/(?P<topicrevision_id>\d+)/edit/$', 'topicrevision_edit', name='topicrevision_edit'),
    url(r'^topic/$', 'topic_list', name='topic_list'),


    url(r'^meter/$', 'meter_detail', name='meter_detail_default'),
    url(r'^meter/(?P<meter_permalink>[A-Za-z0-9-_.]+)/$', 'meter_detail', name='meter_detail'),

    url(r'^statement/create/$', 'statement_create', name='statement_create'),
    url(r'^statement/(?P<statement_id>\d+)/edit/$', 'statement_edit', name='statement_edit'),
    url(r'^statement/(?P<statement_permalink>[A-Za-z0-9-_.]+)/$', 'statement_detail', name='statement_detail'),
    url(r'^statement/(?P<statement_permalink>[A-Za-z0-9-_.]+)/topic-revision/(?P<topicrevision_id>\d+)/$', 'statement_topicrevision_detail', name='statement_topicrevision_detail'),
    url(r'^statement/$', 'statement_list', name='statement_list'),
    url(r'^statement/tags/(?P<tags_id>\d+)/$', 'statement_tags_detail', name='statement_tags_detail'),
    url(r'^statement/(?P<statement_id>\d+)/item/$', 'statement_item', name='statement_item'),

    # Writer
    url(r'^manage/$', 'manage', name='manage'),
    url(r'^manage/my-statement/$', 'manage_my_statement', name='manage_my_statement'),
    url(r'^manage/my-people/$', 'manage_my_people', name='manage_my_people'),

    # Editor
    url(r'^manage/pending-statement/$', 'manage_pending_statement', name='manage_pending_statement'),
    url(r'^manage/hilight-statement/$', 'manage_hilight_statement', name='manage_hilight_statement'),
    url(r'^manage/promote-statement/$', 'manage_promote_statement', name='manage_promote_statement'),
    url(r'^manage/statement/$', 'manage_statement', name='manage_statement'),
    url(r'^manage/people/$', 'manage_people', name='manage_people'),
    url(r'^manage/information/$', 'manage_information', name='manage_information'),


    url(r'^(?P<inst_name>[A-Za-z0-9-_.]+)/delete/(?P<id>\d+)/$', 'domain_delete', name='domain_delete'),

)

liedetector/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'liedetector.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

polygraph/urls.py
import os
import autocomplete_light
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse
from django.views.generic import TemplateView

autocomplete_light.autodiscover()
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^files-widget/', include('files_widget.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^tagging_autocomplete_tagit/', include('tagging_autocomplete_tagit.urls')),

    url(r'', include('domain.urls', app_name='domain')),

)

# serve static pages
for page in os.listdir(settings.PAGE_ROOT):

    if '.html' in page:

        url_name = page.replace('.html', '')

        urlpatterns += patterns('',
            url(r'^%s/$' % url_name.replace('_', '-'), TemplateView.as_view(template_name=page), name=url_name),
        )


if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^robots\.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", mimetype="text/plain")),
        url(r'^404$', TemplateView.as_view(template_name='404.html')),
        url(r'^500$', TemplateView.as_view(template_name='500.html')),
    )
    

    '''
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
    '''

else:
    urlpatterns += patterns('',
        url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    )

handler503 = 'domain.views.maintenance_mode'

domain/forms.py
import autocomplete_light
from ckeditor.widgets import CKEditorWidget
from django import forms
from django.utils.translation import ugettext_lazy as _

from common.constants import STATUS_CHOICES, STATUS_PUBLISHED

from domain.autocomplete_light_registry import PeopleAutocomplete, TopicAutocomplete, StatementAutocomplete
import files_widget
from common.forms import PermalinkForm, CommonForm
from domain.models import PeopleCategory, People, Topic, Meter, Statement

from tagging.forms import TagField
from tagging_autocomplete_tagit.widgets import TagAutocompleteTagIt

class PeopleEditForm(PermalinkForm):

    permalink = forms.CharField()

    categories = forms.ModelMultipleChoiceField(queryset=PeopleCategory.objects.all(), widget=forms.CheckboxSelectMultiple(attrs={'id': 'id_categories'}))

    first_name = forms.CharField(max_length=255, widget=forms.TextInput())
    last_name = forms.CharField(max_length=255, widget=forms.TextInput())

    occupation = forms.CharField(required=False, max_length=255, widget=forms.TextInput())
    summary = forms.CharField(required=False, widget=forms.Textarea())
    description = forms.CharField(required=False, widget=CKEditorWidget(config_name='default'))
    homepage_url = forms.CharField(required=False, max_length=255, widget=forms.TextInput())

    image = files_widget.forms.FilesFormField(required=False, fields=(forms.CharField(required=False), forms.CharField(required=False), forms.CharField(required=False), ), widget=files_widget.forms.widgets.ImageWidget())

    status = forms.ChoiceField(required=False, widget=forms.RadioSelect(attrs={'id': 'id_status'}), choices=STATUS_CHOICES)


class TopicEditForm(CommonForm):

    title = forms.CharField(max_length=255, widget=forms.TextInput())
    description = forms.CharField(required=False, widget=CKEditorWidget(config_name='default'))

    as_revision = forms.NullBooleanField(widget=forms.CheckboxInput(attrs={'chacked': 'checked'}))


class ReferenceForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control first', 'placeholder': _('Title')}))
    url = forms.URLField(required=False, widget=forms.URLInput(attrs={'class': 'form-control last', 'placeholder': _('URL')}))


class StatementEditForm(PermalinkForm):

    permalink = forms.CharField()

    quote = forms.CharField(widget=CKEditorWidget(config_name='bold'))

    short_detail = forms.CharField(required=False, widget=CKEditorWidget(config_name='minimal'))

    quoted_by = forms.ModelChoiceField(
        queryset=People.objects.all(),
        widget=autocomplete_light.ChoiceWidget(PeopleAutocomplete,
            attrs={'placeholder': _('Type for search people by name'), 'class': 'form-control'}
        )
    )

    source = forms.CharField(required=False, widget=forms.TextInput())

    topic = forms.ModelChoiceField(
        required=False,
        queryset=Topic.objects.all(),
        widget=autocomplete_light.ChoiceWidget(TopicAutocomplete,
            attrs={'placeholder': _('Type for search topic by title'), 'class': 'form-control'}
        )
    )

    tags = TagField(required=False, widget=TagAutocompleteTagIt(max_tags=False))

    meter = forms.ModelChoiceField(
        required=True,
        queryset=Meter.objects.all(),
        empty_label=None,
        widget=forms.RadioSelect(attrs={'id': 'id_meter'})
    )

    relate_statements = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Statement.objects.all(),
        widget=autocomplete_light.MultipleChoiceWidget(StatementAutocomplete,
            attrs={'placeholder': _('Type for search statement by quote or topic title'), 'class': 'form-control'}
        )
    )

    relate_peoples = forms.ModelMultipleChoiceField(
        required=False,
        queryset=People.objects.all(),
        widget=autocomplete_light.MultipleChoiceWidget(PeopleAutocomplete,
            attrs={'placeholder': _('Type for search people by name'), 'class': 'form-control'}
        )
    )

    status = forms.ChoiceField(required=False, widget=forms.RadioSelect(attrs={'id': 'id_status'}), choices=STATUS_CHOICES)
    hilight = forms.NullBooleanField(required=False, widget=forms.CheckboxInput(attrs={'id': 'id_hilight'}))
    promote = forms.NullBooleanField(required=False, widget=forms.CheckboxInput(attrs={'id': 'id_promote'}))

class InformationForm(forms.Form):

    highlight_label = forms.CharField(required=False, max_length=255, widget=forms.TextInput())
    about = forms.CharField(required=False, widget=CKEditorWidget(config_name='default'))
    contact = forms.CharField(required=False, widget=CKEditorWidget(config_name='default'))
    contact_footer = forms.CharField(required=False, widget=CKEditorWidget(config_name='default'))

templates/domain/meter_count.html
{% load common_tags %}
{% load activelink %}
{% load i18n %}
<ul class="block-content item-list row">
    {% for meter, count, percent in meter_statement_count %}
    <li class="item col-md-12 col-xs-6{% if request_meter == meter %} active{% endif %}">

        {% if people %}
        {% if count %}
        <a class="item-inner row" href="{% url 'people_meter' people.permalink meter.permalink %}">
        {% else %}
        <div class="item-inner row">
        {% endif %}
        {% else %}
        <a class="item-inner row" href="{% url 'meter_detail' meter.permalink %}">
        {% endif %}

            <figure class="col-md-3 col-xs-3 left">
                {{ meter.image_small.thumbnail_tag_65x90 }}
            </figure>
            <div class="col-md-9 col-xs-9 right">
                <div class="amount-wrapper">
                    <h3 class="text-fill">
                        <span class="text-fill-inner">
                            {{ meter.title }}
                        </span>
                    </h3>
                    <div class="amount-bar"><div class="amount" style="width:{{ percent }}%;"></div></div>
                </div>
                <div class="amount-num">
                    <span class="text-large">{{ count }}</span> {% trans 'statements' %}
                </div>
            </div>
         {% if not people or count %}
         </a>
         {% else %}
         </div>
         {% endif %}

    </li>
    {% endfor %}
</ul>

templates/domain/people_edit.html
{% extends 'base_single.html' %}
{% load i18n %}

{% block title %}{% trans "Your profile settings" %}{% endblock %}

{% block content_class %} content-thin{% endblock %}

{% block content %}

<form method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.media }}

    {% if form.non_field_errors %}
    <div class="errors alert alert-danger">{{ form.non_field_errors }}</div>
    {% endif %}

    <div class="controls form-group">
        <label for="id_permalink" class="col-sm-4 control-label">{% trans "Permalink" %}</label>
        <div class="col-sm-8">
            <input id="id_permalink" name="permalink" type="text" class="form-control" value="{{ form.permalink.value|default_if_none:"" }}" required>
            {% if form.permalink.errors %}
            <div class="errors alert alert-danger">{{ form.permalink.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_first_name" class="col-sm-4 control-label">{% trans "First name" %}</label>
        <div class="col-sm-8">
            <input id="id_first_name" name="first_name" type="text" class="form-control" value="{{ form.first_name.value|default_if_none:"" }}">
            {% if form.first_name.errors %}
            <div class="errors alert alert-danger">{{ form.first_name.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_last_name" class="col-sm-4 control-label">{% trans "Last name" %}</label>
        <div class="col-sm-8">
            <input id="id_last_name" name="last_name" type="text" class="form-control" value="{{ form.last_name.value|default_if_none:"" }}">
            {% if form.last_name.errors %}
            <div class="errors alert alert-danger">{{ form.last_name.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_occupation" class="col-sm-4 control-label">{% trans "Occupation" %}</label>
        <div class="col-sm-8">
            <input id="id_occupation" name="occupation" type="text" class="form-control" value="{{ form.occupation.value|default_if_none:"" }}">
            {% if form.occupation.errors %}
            <div class="errors alert alert-danger">{{ form.occupation.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_description" class="col-sm-4 control-label">{% trans "Description" %}</label>
        <div class="col-sm-8">
            {{ form.description }}
            {% if form.description.errors %}
            <div class="errors alert alert-danger">{{ form.description.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_homepage_url" class="col-sm-4 control-label">{% trans "Homepage url" %}</label>
        <div class="col-sm-8">
            <input id="id_homepage_url" name="homepage_url" type="text" class="form-control" value="{{ form.homepage_url.value|default_if_none:"" }}">
            {% if form.homepage_url.errors %}
            <div class="errors alert alert-danger">{{ form.homepage_url.errors }}</div>
            {% endif %}
        </div>
    </div>


    <div class="col-sm-offset-4 col-sm-8 form-action">
        <button class="btn btn-primary" type="submit">{% trans "Save changes" %}</button>
        <a href="{% url 'home' %}" class="btn btn-cancle flat-btn">{% trans "Cancel" %}</a>
    </div>

</form>
{% endblock %}

templates/domain/people_form.html
{% extends 'base_single.html' %}
{% load i18n %}
{% load staticfiles %}

{% block js %}
{{ form.media.js }}
<script type="text/javascript" src="{% static 'libs/prettycheckable/js/prettycheckable.js' %}"></script>
{% endblock %}
{% block css %}
{{ form.media.css }}
<link href="{% static 'libs/prettycheckable/css/prettycheckable.css' %}" type="text/css" rel="stylesheet">
{% endblock %}

{% block title %}
{% if form.is_new %}{% trans "Create" %}{% else %}{% trans "Edit" %}{% endif %} {% trans form.inst.inst_name %}
{% if not form.is_new and not request_popup %}
<a href="{% url 'people_detail' form.inst.permalink %}" class="btn btn-default btn-xs btn-view">
    <span class="glyphicon glyphicon-eye-open"></span> {% trans "View result" %}
</a>
{% endif %}
{% endblock %}
{% block content_class %} content-smart{% endblock %}


{% block breadcrumb %}
<li><a href="{% url 'people_list' %}">{% trans "People" %}</a></li>
{% if form.is_new %}
<li class="active">{% trans "Create" %}</li>
{% else %}
<li><a href="{% url 'people_detail' form.inst.permalink %}">{{ form.inst.get_full_name }}</a></li>
<li class="active">{% trans "Edit" %}</li>
{% endif %}
{% endblock %}


{% block content %}
<form method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
    {% csrf_token %}

    {% if form.non_field_errors %}
    <div class="errors alert alert-danger">{{ form.non_field_errors }}</div>
    {% endif %}

    <div class="controls form-group">
        <label for="id_permalink" class="col-sm-2 control-label">{% trans "Permalink" %} *</label>


        <div class="col-sm-10">

            <input disabled="disabled" readonly="readonly" id="id_permalink_readonly" name="permalink_readonly" type="text" class="form-control" value="{{ form.permalink.value|default_if_none:"" }}">
            <a id="edit-permalink" href="#id_permalink">{% trans "edit" %}</a>

            <input id="id_permalink" name="permalink" type="text" class="form-control" value="{{ form.permalink.value|default_if_none:"" }}" required>
            <span class="help-block">{{ form.permalink.help_text }}</span>
            {% if form.permalink.errors %}
            <div class="errors alert alert-danger">{{ form.permalink.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_first_name" class="col-sm-2 control-label">{% trans "First name" %} *</label>
        <div class="col-sm-10">
            <input id="id_first_name" name="first_name" type="text" class="form-control" value="{{ form.first_name.value|default_if_none:"" }}">
            {% if form.first_name.errors %}
            <div class="errors alert alert-danger">{{ form.first_name.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_last_name" class="col-sm-2 control-label">{% trans "Last name" %} *</label>
        <div class="col-sm-10">
            <input id="id_last_name" name="last_name" type="text" class="form-control" value="{{ form.last_name.value|default_if_none:"" }}">
            {% if form.last_name.errors %}
            <div class="errors alert alert-danger">{{ form.last_name.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_occupation" class="col-sm-2 control-label">{% trans "Occupation" %}</label>
        <div class="col-sm-10">
            <input id="id_occupation" name="occupation" type="text" class="form-control" value="{{ form.occupation.value|default_if_none:"" }}">
            <span class="help-block">{% trans "Display on the people list page." %}</span>
            {% if form.occupation.errors %}
            <div class="errors alert alert-danger">{{ form.occupation.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_categories" class="col-sm-2 control-label">{% trans "Categories" %} *</label>
        <div class="col-sm-10 checkbox">
            <ul>
                {% for category in form.categories %}
                <li>
                    {{ category.tag }}
                    <label for="id_categories_{{ category.index }}">{{ category.choice_label }}</label>
                </li>
                {% endfor %}
            </ul>

            {% if form.categories.errors %}
            <div class="errors alert alert-danger">{{ form.categories.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_summary" class="col-sm-2 control-label">{% trans "Summary" %}</label>
        <div class="col-sm-10">
            <textarea name="summary" class="form-control">{{ form.summary.value|default_if_none:"" }}</textarea>
            <span class="help-block">
                {% trans "The text should not lengthy for display on the top of people detail page. Automatically display occupation field instead of blank summary." %}
            </span>
            {% if form.summary.errors %}
            <div class="errors alert alert-danger">{{ form.summary.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_description" class="col-sm-2 control-label">{% trans "Description" %}</label>
        <div class="col-sm-10">
            {{ form.description }}
            <span class="help-block">
                {% trans "History of work, education, business, family,  ..." %}
            </span>
            {% if form.description.errors %}
            <div class="errors alert alert-danger">{{ form.description.errors }}</div>
            {% endif %}
        </div>
    </div>

    <div class="controls form-group">
        <label for="id_homepage_url" class="col-sm-2 control-label">{% trans "Homepage" %}</label>
        <div class="col-sm-10">
            <input id="id_homepage_url" name="homepage_url" type="text" class="form-control" value="{{ form.homepage_url.value|default_if_none:"" }}">
            <span class="help-block">
                {% trans "URL of people homapage. Include http:// on this field." %}
            </span>
            {% if form.homepage_url.errors %}
            <div class="errors alert alert-danger">{{ form.homepage_url.errors }}</div>
            {% endif %}
        </div>
    </div>


    <div class="controls form-group">
        <label for="id_image" class="col-sm-2 control-label">{% trans "Picture" %}</label>
        <div class="col-sm-10">
            {{ form.image }}
            <span class="help-block">
                {% trans "Should be square photo and face on the center." %}
            </span>
            {% if form.image.errors %}
            <div class="errors alert alert-danger">{{ form.image.errors }}</div>
            {% endif %}
        </div>
    </div>


    <div class="controls form-group inst-status">
        <label for="id_status" class="col-sm-2 control-label">{% trans "Status" %}</label>
        <div class="col-sm-10 radio">
            {% for status in form.status %}
                {{ status.tag }}
                 <label for="id_status_{{ status.index }}">{{ status.choice_label }}</label>
            {% endfor %}

            {% if form.status.errors %}
            <div class="errors alert alert-danger">{{ form.status.errors }}</div>
            {% endif %}
        </div>
    </div>



    <div class="controls form-group">
        <div class="col-sm-offset-2 col-sm-10 form-action">
            <button class="btn btn-primary" type="submit">{% if form.is_new %}{% trans "Save new" %}{% else %}{% trans "Save changes" %}{% endif %}</button>
            {% if not request_popup %}
            <a href="." class="btn btn-cancle flat-btn">{% trans "Cancel" %}</a>

            {% if not form.is_new %}
            <a class="btn btn-delete" href="{% url 'domain_delete' 'people' form.inst.id %}"><span class="glyphicon glyphicon-remove"></span> {% trans "Delete" %}</a>
            {% endif %}

            {% endif %}
        </div>
    </div>
</form>

<script type="text/javascript">
    {% if form.is_new %}
    generatePermalink($('input[name=first_name]'));
    {% endif %}
    controlPermalink()
    preventScrollReload()
</script>

{% endblock %}

templates/domain/topic_inline_form.html
{% load i18n %}
{% load common_tags %}

<div class="controls form-group">
    <label for="id_title" class="{% if not request_inline %}col-sm-2 {% endif %}control-label">{% trans "Title" %} *</label>
    <div class="{% if not request_inline %}col-sm-10{% endif %}">
        <input id="id_title" name="title" type="text" class="form-control" value="{{ form.title.value|default_if_none:"" }}">
        {% if form.title.errors %}
        <div class="errors alert alert-danger">{{ form.title.errors }}</div>
        {% endif %}
    </div>
</div>

<div class="controls form-group">
    <label for="id_description" class="{% if not request_inline %}col-sm-2 {% endif %}control-label">{% trans "Description" %}</label>
    <div class="{% if not request_inline %}col-sm-10{% endif %}">
        {{ form.description }}
        {% if form.description.errors %}
        <div class="errors alert alert-danger">{{ form.description.errors }}</div>
        {% endif %}
    </div>
</div>

{% if not form.is_new %}
<div class="controls form-group">
    <label class="{% if not request_inline %}col-sm-2 {% endif %}control-label">{% trans "Revision" %}</label>
    <div class="{% if not request_inline %}col-sm-10 checkbox{% endif %}">
        <input{% if not form.as_revision.value %} checked=checked{% endif %} id="id_{{ form.as_revision.name }}" type="checkbox" name="{{ form.as_revision.name }}" value="1" />
        <label for="id_{{ form.as_revision.name }}">{% trans "Save as new revision" %}</label>
        {% if form.as_revision.errors %}
        <div class="errors alert alert-danger">{{ form.as_revision.errors }}</div>
        {% endif %}
    </div>
</div>
{% endif %}

<div class="controls form-group">
    <div class="{% if not request_inline %}col-sm-offset-2 col-sm-10 {% endif %}form-action">
        <button class="btn btn-primary" type="submit">{% if form.is_new %}{% trans "Save new" %}{% else %}{% trans "Save changes" %}{% endif %}</button>
        <a href="." class="btn btn-cancel flat-btn">{% trans "Cancel" %}</a>

        {% if not form.is_new %}
        <a class="btn btn-delete" href="{% url 'domain_delete' 'topic' form.inst.id %}"><span class="glyphicon glyphicon-remove"></span> {% trans "Delete" %}</a>
        {% endif %}

    </div>
</div>


{% if request_inline %}
<script type="text/javascript">

    (function ($) {


        {% if form.is_valid %}

        var win = {
            'name': 'id_topic',
            'close': function () {
                //delete(CKEDITOR.instances.id_description);
                $('.add-another-inline-input-list').html('');

            }
        };

        dismissAddAnotherPopup(win, '{{ form.inst.id }}', '{{ form.inst.id|topic_render_reference|safe }}');

        {% else %}


        $('.add-another-inline-input-list .btn-cancel').click(function (e) {
            e.preventDefault();
            $('.add-another-inline-input-list').html('');
            $('#inline_overlay').remove();
        });

        $('.add-another-inline-input-list .btn-primary').click(function (e) {
            e.preventDefault();

            if (CKEDITOR.instances.id_description) {
                $('#id_description').val(CKEDITOR.instances.id_description.getData());
            }

            var input_list_container = $(this).parents('.add-another-inline-input-list');
            var input_list = input_list_container.find('[name]');

            var params = {'_inline': '1'};
            input_list.each(function () {
                if ($(this).attr('type') == 'checkbox') {
                    params[$(this).attr('name')] = 0+$(this).prop('checked');
                }
                else {
                    params[$(this).attr('name')] = $(this).val();
                }
            });

            var topic_post_url = '{% if form.is_new %}{% url 'topic_create' %}{% else %}{% url 'topic_edit' form.inst.id %}{% endif %}';


            input_list_container.load(topic_post_url, params);

            $('#inline_overlay').remove();


        });

        $('.inline-reference-wrapper').append('<div id="inline_overlay"></div>');

        {% endif %}


        // confirm delete
        $('.btn-delete').popConfirm({
            title: "{% trans "Delete Item" %}",
            content: "{% trans "Are you sure you want to delete this item?" %}",
            placement: "top"
        });


    }) (jQuery);

</script>
{% endif %}


<script type="text/javascript">

    (function ($) {


        var as_revision = $('#id_{{ form.as_revision.name }}');

        if (as_revision.length) {

            as_revision.removeAttr('checked');

            {% if request_inline %}
            as_revision.prettyCheckable();
            {% endif %}

            var ignore_check_as_revision  = false;

            var check_data_change = function (is_changed) {
                if (is_changed === true || (!ignore_check_as_revision && this.checkDirty())) {
                    as_revision.attr('checked', 'checked').siblings().addClass('checked');
                }
            }

            if (CKEDITOR.instances.id_description) {
                CKEDITOR.instances.id_description.on('blur', check_data_change);
            }

            $('input[name=title]').change(function () {check_data_change(true)});



            setTimeout(function () {
                as_revision.siblings().click(function () {
                    ignore_check_as_revision  = true;
                });
            }, 1000);
        }


    }) (jQuery);

</script>